### ISSUE TITLE
Web3 Error Extractor Returning null 

### ISSUE THREAD

**Issue by codewithabbass** [moazzamgodil/web3-errors-extract#1]
I encountered an error while executing a transaction. The transaction was reverted by the Ethereum Virtual Machine (EVM). Additionally, the Web3 Error Extractor is showing a null result sometimes, even though the original error contains all the necessary data.

original Error is:
`{
  "blockHash": "XXXX",
  "blockNumber": 6512908,
  "contractAddress": null,
  "cumulativeGasUsed": 5355691,
  "effectiveGasPrice": 3265809017,
  "from": "XXXX",
  "gasUsed": 2957556,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "XXXX",
  "transactionHash": "XXXX",
  "transactionIndex": 5,
  "type": "0x2",
  "events": {}
}
`

Web3 Error Extractor: => 
`null`

**Comment by moazzamgodil** [comment]
Fixed issue in [v0.2.1](https://www.npmjs.com/package/web3-errors-extract/v/0.2.1)
